### ISSUE TITLE
Youtube links in http

### ISSUE THREAD

**Issue by icco** [divan/blog#2]
This may be a bug in hugo and not your blog... but if you view https://divan.github.io/posts/go_concurrency_visualize/ on https, you get a few mixed content warnings because your youtube video embeds are http and not https.

> Mixed Content: The page at 'https://divan.github.io/posts/go_concurrency_visualize/' was loaded over HTTPS, but requested an insecure resource 'http://www.youtube.com/embed/cN_DpYBzKso'. This content should also be served over HTTPS.

Looking at [the hugo docs](https://gohugo.io/extras/shortcodes/#youtube), they imply that the embed should be https, so not sure what's happening.

**Comment by divan** [comment]
Hey @icco, thanks for pointing this out, I wasn't aware of this error message.

Just in case, is this causing any visible problem on any browser/platform? Or it's just warning in a JS console for you as well?

**Comment by icco** [comment]
@divan it makes it so none of the youtube embeded videos load (they are just big whitespaces) until you click "load unsafe scripts" in the url bar.

**Comment by icco** [comment]
This is on chrome btw, not sure about other browsers.
